// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TriHalo.API.Models;

namespace TriHalo.API.Migrations
{
    [DbContext(typeof(TsurugiContext))]
    partial class TsurugiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview7.19362.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TriHalo.Common.Tsurugi.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ReferenceURL");

                    b.HasKey("ID");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("TriHalo.Common.Tsurugi.Chapter", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Number");

                    b.Property<int?>("ParentID");

                    b.Property<string>("ReferenceURL");

                    b.HasKey("ID");

                    b.HasIndex("ParentID");

                    b.ToTable("Chapter");
                });

            modelBuilder.Entity("TriHalo.Common.Tsurugi.Sentence", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Number");

                    b.Property<int?>("ParentID");

                    b.HasKey("ID");

                    b.HasIndex("ParentID");

                    b.ToTable("Sentence");
                });

            modelBuilder.Entity("TriHalo.Common.Tsurugi.Book", b =>
                {
                    b.OwnsOne("TriHalo.Common.Text", "Title", b1 =>
                        {
                            b1.Property<int>("BookID")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Original");

                            b1.Property<string>("Ruby");

                            b1.HasKey("BookID");

                            b1.ToTable("Book");

                            b1.WithOwner()
                                .HasForeignKey("BookID");
                        });
                });

            modelBuilder.Entity("TriHalo.Common.Tsurugi.Chapter", b =>
                {
                    b.HasOne("TriHalo.Common.Tsurugi.Book", "Parent")
                        .WithMany("Chapters")
                        .HasForeignKey("ParentID");

                    b.OwnsOne("TriHalo.Common.Text", "Title", b1 =>
                        {
                            b1.Property<int>("ChapterID")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Original");

                            b1.Property<string>("Ruby");

                            b1.HasKey("ChapterID");

                            b1.ToTable("Chapter");

                            b1.WithOwner()
                                .HasForeignKey("ChapterID");
                        });
                });

            modelBuilder.Entity("TriHalo.Common.Tsurugi.Sentence", b =>
                {
                    b.HasOne("TriHalo.Common.Tsurugi.Chapter", "Parent")
                        .WithMany("Sentences")
                        .HasForeignKey("ParentID");

                    b.OwnsOne("TriHalo.Common.Text", "Text", b1 =>
                        {
                            b1.Property<int>("SentenceID")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Original");

                            b1.Property<string>("Ruby");

                            b1.HasKey("SentenceID");

                            b1.ToTable("Sentence");

                            b1.WithOwner()
                                .HasForeignKey("SentenceID");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
