// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TriHalo.API.Models;

namespace TriHalo.API.Migrations
{
    [DbContext(typeof(TsurugiContext))]
    partial class TsurugiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview7.19362.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TriHalo.Common.Text", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Original");

                    b.Property<string>("Ruby");

                    b.HasKey("ID");

                    b.ToTable("Text");
                });

            modelBuilder.Entity("TriHalo.Common.Tsurugi.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ReferenceURL");

                    b.Property<int?>("TitleID");

                    b.HasKey("ID");

                    b.HasIndex("TitleID");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("TriHalo.Common.Tsurugi.Chapter", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Number");

                    b.Property<int?>("ParentID");

                    b.Property<string>("ReferenceURL");

                    b.Property<int?>("TitleID");

                    b.HasKey("ID");

                    b.HasIndex("ParentID");

                    b.HasIndex("TitleID");

                    b.ToTable("Chapter");
                });

            modelBuilder.Entity("TriHalo.Common.Tsurugi.Sentence", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Number");

                    b.Property<int?>("ParentID");

                    b.Property<int?>("TextID");

                    b.HasKey("ID");

                    b.HasIndex("ParentID");

                    b.HasIndex("TextID");

                    b.ToTable("Sentence");
                });

            modelBuilder.Entity("TriHalo.Common.Tsurugi.Book", b =>
                {
                    b.HasOne("TriHalo.Common.Text", "Title")
                        .WithMany()
                        .HasForeignKey("TitleID");
                });

            modelBuilder.Entity("TriHalo.Common.Tsurugi.Chapter", b =>
                {
                    b.HasOne("TriHalo.Common.Tsurugi.Book", "Parent")
                        .WithMany("Chapters")
                        .HasForeignKey("ParentID");

                    b.HasOne("TriHalo.Common.Text", "Title")
                        .WithMany()
                        .HasForeignKey("TitleID");
                });

            modelBuilder.Entity("TriHalo.Common.Tsurugi.Sentence", b =>
                {
                    b.HasOne("TriHalo.Common.Tsurugi.Chapter", "Parent")
                        .WithMany("Sentences")
                        .HasForeignKey("ParentID");

                    b.HasOne("TriHalo.Common.Text", "Text")
                        .WithMany()
                        .HasForeignKey("TextID");
                });
#pragma warning restore 612, 618
        }
    }
}
